#!/bin/sh
cd /home/shepherd/blog
hexo clean
hexo g
cd ./public
git init
git remote add origin git@github.com:shepherdev/shepherdev.github.io.git
git add .
git commit -m "Bash Auto Builder at $(date +'%Y-%m-%d')"
git push --force origin master
